### ISSUE TITLE
How do we assign LAN IP addresses?

### ISSUE THREAD

**Issue by jacobwilliams100** [RigPig/SYS-265-Final#3]
I do not know which static LAN IP addresses to assign to the hosts on this system. Can it be arbitrary, or do we have assignments for them?

**Comment by RigPig** [comment]
If you look at the final project and group assessment doc, he has listed all IPs for us to use

**Comment by RigPig** [comment]
If you look at the final project and group assessment doc, he has listed all IPs for us to use
