### ISSUE TITLE
AD DC could not be contacted

### ISSUE THREAD

**Issue by RigPig** [RigPig/SYS-265-Final#4]
![image](https://github.com/RigPig/SYS-265-Final/assets/90580134/688777f0-343b-49c8-9ac3-05cfd6cf19db)

**Comment by jacobwilliams100** [comment]
Also not working from workstation 1

**Comment by jacobwilliams100** [comment]
I think it has something to do with DNS

**Comment by jacobwilliams100** [comment]
We fixed it. Necessary steps:
-Set up Domain admin and DNS on DC1
-Add A/Pointer records to DNS on DC1
-Set the client's DNS to DC1 (172.16.1.12)
-Restart DC1 for good measure
