### ISSUE TITLE
What are some good ideas of applications to deploy via Docker?

### ISSUE THREAD

**Issue by jacobwilliams100** [RigPig/SYS-265-Final#9]
I have Docker working. I need help thinking of a wiki/application to deploy via Docker. It can't be WordPress. Any ideas?

**Comment by RigPig** [comment]
Is just a basic web server possible?

**Comment by jacobwilliams100** [comment]
I found another wiki platform called Bookstack that looks simple and easy. Going to try that.

**Comment by jacobwilliams100** [comment]
Implemented, Functioning, and Documented.
